name: Build & deploy dashboard

on:
  push:
    branches:
      - main 

jobs:
  jekyll:
    runs-on: ubuntu-20.04 
    steps:
      - uses: actions/checkout@v2

      - name: Build & deploy dashboard
        uses: jeffreytse/jekyll-deploy-action@v0.3.0 
        with:
          provider: 'github'
          token: ${{ secrets.GITHUB_TOKEN }}
          jekyll_src: './' 
          jekyll_cfg: '_config.yml'
          jekyll_baseurl: ''
          cname: 'settings.yeahgames.net'